flags: {}
extra-package-dbs: []
packages:
- '.'
- codec-jvm
- utils/eta-pkgdb
- utils/eta-pkg
- epm/epm
- epm/Cabal
- location: http://github.com/mrkkrp/zip/archive/0363e1664cebbb0b5b4ebe5a6aba7a6e499b18c2.zip
extra-deps:
- aeson-1.0.2.1
- mmorph-1.0.9
- optparse-applicative-0.13.0.0
- turtle-1.3.0
- unix-compat-0.4.3.1
- zip-0.1.7
resolver: lts-6.27
